export const LANGUAGES = [
  {
    iso_3166_1: 'xx',
    english_name: 'None Selected',
    name: 'None Selected',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ab',
    english_name: 'Abkhazian',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'aa',
    english_name: 'Afar',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'af',
    english_name: 'Afrikaans',
    name: 'Afrikaans',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ak',
    english_name: 'Akan',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'sq',
    english_name: 'Albanian',
    name: 'shqip',
    image_id: undefined,
  },
  {
    iso_3166_1: 'am',
    english_name: 'Amharic',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ar',
    english_name: 'Arabic',
    name: 'العربية',
    image_id: undefined,
  },
  {
    iso_3166_1: 'an',
    english_name: 'Aragonese',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'hy',
    english_name: 'Armenian',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'as',
    english_name: 'Assamese',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'av',
    english_name: 'Avaric',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ae',
    english_name: 'Avestan',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ay',
    english_name: 'Aymara',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'az',
    english_name: 'Azerbaijani',
    name: 'Azərbaycan',
    image_id: undefined,
  },
  {
    iso_3166_1: 'bm',
    english_name: 'Bambara',
    name: 'Bamanankan',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ba',
    english_name: 'Bashkir',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'eu',
    english_name: 'Basque',
    name: 'euskera',
    image_id: undefined,
  },
  {
    iso_3166_1: 'be',
    english_name: 'Belarusian',
    name: 'беларуская мова',
    image_id: undefined,
  },
  {
    iso_3166_1: 'bn',
    english_name: 'Bengali',
    name: 'বাংলা',
    image_id: undefined,
  },
  {
    iso_3166_1: 'bi',
    english_name: 'Bislama',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'bs',
    english_name: 'Bosnian',
    name: 'Bosanski',
    image_id: undefined,
  },
  {
    iso_3166_1: 'br',
    english_name: 'Breton',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'bg',
    english_name: 'Bulgarian',
    name: 'български език',
    image_id: undefined,
  },
  {
    iso_3166_1: 'my',
    english_name: 'Burmese',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'cn',
    english_name: 'Cantonese',
    name: '广州话 / 廣州話',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ca',
    english_name: 'Catalan',
    name: 'Català',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ch',
    english_name: 'Chamorro',
    name: "Finu' Chamorro",
    image_id: undefined,
  },
  {
    iso_3166_1: 'ce',
    english_name: 'Chechen',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ny',
    english_name: 'Chichewa; Nyanja',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'cv',
    english_name: 'Chuvash',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'kw',
    english_name: 'Cornish',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'co',
    english_name: 'Corsican',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'cr',
    english_name: 'Cree',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'hr',
    english_name: 'Croatian',
    name: 'Hrvatski',
    image_id: undefined,
  },
  {
    iso_3166_1: 'cs',
    english_name: 'Czech',
    name: 'Český',
    image_id: undefined,
  },
  {
    iso_3166_1: 'da',
    english_name: 'Danish',
    name: 'Dansk',
    image_id: undefined,
  },
  {
    iso_3166_1: 'dv',
    english_name: 'Divehi',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'nl',
    english_name: 'Dutch',
    name: 'Nederlands',
    image_id: undefined,
  },
  {
    iso_3166_1: 'dz',
    english_name: 'Dzongkha',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'en',
    english_name: 'English',
    name: 'English',
    image_id: undefined,
  },
  {
    iso_3166_1: 'eo',
    english_name: 'Esperanto',
    name: 'Esperanto',
    image_id: undefined,
  },
  {
    iso_3166_1: 'et',
    english_name: 'Estonian',
    name: 'Eesti',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ee',
    english_name: 'Ewe',
    name: 'Èʋegbe',
    image_id: undefined,
  },
  {
    iso_3166_1: 'fo',
    english_name: 'Faroese',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'fj',
    english_name: 'Fijian',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'fi',
    english_name: 'Finnish',
    name: 'suomi',
    image_id: undefined,
  },
  {
    iso_3166_1: 'fr',
    english_name: 'French',
    name: 'Français',
    image_id: undefined,
  },
  {
    iso_3166_1: 'fy',
    english_name: 'Frisian',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ff',
    english_name: 'Fulah',
    name: 'Fulfulde',
    image_id: undefined,
  },
  {
    iso_3166_1: 'gd',
    english_name: 'Gaelic',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'gl',
    english_name: 'Gallegan',
    name: 'Galego',
    image_id: undefined,
  },
  {
    iso_3166_1: 'lg',
    english_name: 'Ganda',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ka',
    english_name: 'Georgian',
    name: 'ქართული',
    image_id: undefined,
  },
  {
    iso_3166_1: 'de',
    english_name: 'German',
    name: 'Deutsch',
    image_id: undefined,
  },
  {
    iso_3166_1: 'el',
    english_name: 'Greek',
    name: 'ελληνικά',
    image_id: undefined,
  },
  {
    iso_3166_1: 'gn',
    english_name: 'Guarani',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'gu',
    english_name: 'Gujarati',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ht',
    english_name: 'Haitian; Haitian Creole',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ha',
    english_name: 'Hausa',
    name: 'Hausa',
    image_id: undefined,
  },
  {
    iso_3166_1: 'he',
    english_name: 'Hebrew',
    name: 'עִבְרִית',
    image_id: undefined,
  },
  {
    iso_3166_1: 'hz',
    english_name: 'Herero',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'hi',
    english_name: 'Hindi',
    name: 'हिन्दी',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ho',
    english_name: 'Hiri Motu',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'hu',
    english_name: 'Hungarian',
    name: 'Magyar',
    image_id: undefined,
  },
  {
    iso_3166_1: 'is',
    english_name: 'Icelandic',
    name: 'Íslenska',
    image_id: undefined,
  },
  {
    iso_3166_1: 'io',
    english_name: 'Ido',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ig',
    english_name: 'Igbo',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'id',
    english_name: 'Indonesian',
    name: 'Bahasa indonesia',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ia',
    english_name: 'Interlingua',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ie',
    english_name: 'Interlingue',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'iu',
    english_name: 'Inuktitut',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ik',
    english_name: 'Inupiaq',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ga',
    english_name: 'Irish',
    name: 'Gaeilge',
    image_id: undefined,
  },
  {
    iso_3166_1: 'it',
    english_name: 'Italian',
    name: 'Italiano',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ja',
    english_name: 'Japanese',
    name: '日本語',
    image_id: undefined,
  },
  {
    iso_3166_1: 'jv',
    english_name: 'Javanese',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'kl',
    english_name: 'Kalaallisut',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'kn',
    english_name: 'Kannada',
    name: '?????',
    image_id: undefined,
  },
  {
    iso_3166_1: 'kr',
    english_name: 'Kanuri',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ks',
    english_name: 'Kashmiri',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'kk',
    english_name: 'Kazakh',
    name: 'қазақ',
    image_id: undefined,
  },
  {
    iso_3166_1: 'km',
    english_name: 'Khmer',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ki',
    english_name: 'Kikuyu',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'rw',
    english_name: 'Kinyarwanda',
    name: 'Kinyarwanda',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ky',
    english_name: 'Kirghiz',
    name: '??????',
    image_id: undefined,
  },
  {
    iso_3166_1: 'kv',
    english_name: 'Komi',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'kg',
    english_name: 'Kongo',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ko',
    english_name: 'Korean',
    name: '한국어/조선말',
    image_id: undefined,
  },
  {
    iso_3166_1: 'kj',
    english_name: 'Kuanyama',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ku',
    english_name: 'Kurdish',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'lo',
    english_name: 'Lao',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'la',
    english_name: 'Latin',
    name: 'Latin',
    image_id: undefined,
  },
  {
    iso_3166_1: 'lv',
    english_name: 'Latvian',
    name: 'Latviešu',
    image_id: undefined,
  },
  {
    iso_3166_1: 'lb',
    english_name: 'Letzeburgesch',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'li',
    english_name: 'Limburgish',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ln',
    english_name: 'Lingala',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'lt',
    english_name: 'Lithuanian',
    name: 'Lietuvikai',
    image_id: undefined,
  },
  {
    iso_3166_1: 'lu',
    english_name: 'Luba-Katanga',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'mk',
    english_name: 'Macedonian',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'mg',
    english_name: 'Malagasy',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ms',
    english_name: 'Malay',
    name: 'Bahasa melayu',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ml',
    english_name: 'Malayalam',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'mt',
    english_name: 'Maltese',
    name: 'Malti',
    image_id: undefined,
  },
  {
    iso_3166_1: 'zh',
    english_name: 'Mandarin',
    name: '普通话',
    image_id: undefined,
  },
  {
    iso_3166_1: 'gv',
    english_name: 'Manx',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'mi',
    english_name: 'Maori',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'mr',
    english_name: 'Marathi',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'mh',
    english_name: 'Marshall',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'mo',
    english_name: 'Moldavian',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'mn',
    english_name: 'Mongolian',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'na',
    english_name: 'Nauru',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'nv',
    english_name: 'Navajo',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'nr',
    english_name: 'Ndebele',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'nd',
    english_name: 'Ndebele',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ng',
    english_name: 'Ndonga',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ne',
    english_name: 'Nepali',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'se',
    english_name: 'Northern Sami',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'no',
    english_name: 'Norwegian',
    name: 'Norsk',
    image_id: undefined,
  },
  {
    iso_3166_1: 'nb',
    english_name: 'Norwegian Bokmål',
    name: 'Bokmål',
    image_id: undefined,
  },
  {
    iso_3166_1: 'nn',
    english_name: 'Norwegian Nynorsk',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'oc',
    english_name: 'Occitan',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'oj',
    english_name: 'Ojibwa',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'or',
    english_name: 'Oriya',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'om',
    english_name: 'Oromo',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'os',
    english_name: 'Ossetian; Ossetic',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'pi',
    english_name: 'Pali',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'fa',
    english_name: 'Persian',
    name: 'فارسی',
    image_id: undefined,
  },
  {
    iso_3166_1: 'pl',
    english_name: 'Polish',
    name: 'Polski',
    image_id: undefined,
  },
  {
    iso_3166_1: 'pt',
    english_name: 'Portuguese',
    name: 'Português',
    image_id: undefined,
  },
  {
    iso_3166_1: 'pa',
    english_name: 'Punjabi',
    name: 'ਪੰਜਾਬੀ',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ps',
    english_name: 'Pushto',
    name: 'پښتو',
    image_id: undefined,
  },
  {
    iso_3166_1: 'qu',
    english_name: 'Quechua',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'rm',
    english_name: 'Raeto-Romance',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ro',
    english_name: 'Romanian',
    name: 'Română',
    image_id: undefined,
  },
  {
    iso_3166_1: 'rn',
    english_name: 'Rundi',
    name: 'Kirundi',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ru',
    english_name: 'Russian',
    name: 'Pусский',
    image_id: undefined,
  },
  {
    iso_3166_1: 'sm',
    english_name: 'Samoan',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'sg',
    english_name: 'Sango',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'sa',
    english_name: 'Sanskrit',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'sc',
    english_name: 'Sardinian',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'sr',
    english_name: 'Serbian',
    name: 'Srpski',
    image_id: undefined,
  },
  {
    iso_3166_1: 'sh',
    english_name: 'Serbo-Croatian',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'sn',
    english_name: 'Shona',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'sd',
    english_name: 'Sindhi',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'si',
    english_name: 'Sinhalese',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'cu',
    english_name: 'Slavic',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'sk',
    english_name: 'Slovak',
    name: 'Slovenčina',
    image_id: undefined,
  },
  {
    iso_3166_1: 'sl',
    english_name: 'Slovenian',
    name: 'Slovenščina',
    image_id: undefined,
  },
  {
    iso_3166_1: 'so',
    english_name: 'Somali',
    name: 'Somali',
    image_id: undefined,
  },
  {
    iso_3166_1: 'st',
    english_name: 'Sotho',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'es',
    english_name: 'Spanish',
    name: 'Español',
    image_id: undefined,
  },
  {
    iso_3166_1: 'su',
    english_name: 'Sundanese',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'sw',
    english_name: 'Swahili',
    name: 'Kiswahili',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ss',
    english_name: 'Swati',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'sv',
    english_name: 'Swedish',
    name: 'svenska',
    image_id: undefined,
  },
  {
    iso_3166_1: 'tl',
    english_name: 'Tagalog',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ty',
    english_name: 'Tahitian',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'tg',
    english_name: 'Tajik',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ta',
    english_name: 'Tamil',
    name: 'தமிழ்',
    image_id: undefined,
  },
  {
    iso_3166_1: 'tt',
    english_name: 'Tatar',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'te',
    english_name: 'Telugu',
    name: 'తెలుగు',
    image_id: undefined,
  },
  {
    iso_3166_1: 'th',
    english_name: 'Thai',
    name: 'ภาษาไทย',
    image_id: undefined,
  },
  {
    iso_3166_1: 'bo',
    english_name: 'Tibetan',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ti',
    english_name: 'Tigrinya',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'to',
    english_name: 'Tonga',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ts',
    english_name: 'Tsonga',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'tn',
    english_name: 'Tswana',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'tr',
    english_name: 'Turkish',
    name: 'Türkçe',
    image_id: undefined,
  },
  {
    iso_3166_1: 'tk',
    english_name: 'Turkmen',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'tw',
    english_name: 'Twi',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ug',
    english_name: 'Uighur',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'uk',
    english_name: 'Ukrainian',
    name: 'Український',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ur',
    english_name: 'Urdu',
    name: 'اردو',
    image_id: undefined,
  },
  {
    iso_3166_1: 'uz',
    english_name: 'Uzbek',
    name: 'ozbek',
    image_id: undefined,
  },
  {
    iso_3166_1: 've',
    english_name: 'Venda',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'vi',
    english_name: 'Vietnamese',
    name: 'Tiếng Việt',
    image_id: undefined,
  },
  {
    iso_3166_1: 'vo',
    english_name: 'Volapük',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'wa',
    english_name: 'Walloon',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'cy',
    english_name: 'Welsh',
    name: 'Cymraeg',
    image_id: undefined,
  },
  {
    iso_3166_1: 'wo',
    english_name: 'Wolof',
    name: 'Wolof',
    image_id: undefined,
  },
  {
    iso_3166_1: 'xh',
    english_name: 'Xhosa',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'ii',
    english_name: 'Yi',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'yi',
    english_name: 'Yiddish',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'za',
    english_name: 'Zhuang',
    name: '',
    image_id: undefined,
  },
  {
    iso_3166_1: 'zu',
    english_name: 'Zulu',
    name: 'isiZulu',
    image_id: undefined,
  },
];
