export const OTT_REGIONS = [
  {
    iso_3166_1: 'AR',
    english_name: 'Argentina',
    native_name: 'Argentina',
    image_id: 'AR',
  },
  {
    iso_3166_1: 'AU',
    english_name: 'Australia',
    native_name: 'Australia',
    image_id: 'AU',
  },
  {
    iso_3166_1: 'AT',
    english_name: 'Austria',
    native_name: 'Austria',
    image_id: 'AT',
  },
  {
    iso_3166_1: 'BE',
    english_name: 'Belgium',
    native_name: 'Belgium',
    image_id: 'BE',
  },
  {
    iso_3166_1: 'BR',
    english_name: 'Brazil',
    native_name: 'Brazil',
    image_id: 'BR',
  },
  {
    iso_3166_1: 'BG',
    english_name: 'Bulgaria',
    native_name: 'Bulgaria',
    image_id: 'BG',
  },
  {
    iso_3166_1: 'CA',
    english_name: 'Canada',
    native_name: 'Canada',
    image_id: 'CA',
  },
  {
    iso_3166_1: 'HR',
    english_name: 'Croatia',
    native_name: 'Croatia',
    image_id: 'HR',
  },
  {
    iso_3166_1: 'CZ',
    english_name: 'Czech Republic',
    native_name: 'Czech Republic',
    image_id: 'CZ',
  },
  {
    iso_3166_1: 'DK',
    english_name: 'Denmark',
    native_name: 'Denmark',
    image_id: 'DK',
  },
  {
    iso_3166_1: 'EE',
    english_name: 'Estonia',
    native_name: 'Estonia',
    image_id: 'EE',
  },
  {
    iso_3166_1: 'FI',
    english_name: 'Finland',
    native_name: 'Finland',
    image_id: 'FI',
  },
  {
    iso_3166_1: 'FR',
    english_name: 'France',
    native_name: 'France',
    image_id: 'FR',
  },
  {
    iso_3166_1: 'DE',
    english_name: 'Germany',
    native_name: 'Germany',
    image_id: 'DE',
  },
  {
    iso_3166_1: 'HK',
    english_name: 'Hong Kong',
    native_name: 'Hong Kong SAR China',
    image_id: 'HK',
  },
  {
    iso_3166_1: 'HU',
    english_name: 'Hungary',
    native_name: 'Hungary',
    image_id: 'HU',
  },
  {
    iso_3166_1: 'IN',
    english_name: 'India',
    native_name: 'India',
    image_id: 'IN',
  },
  {
    iso_3166_1: 'ID',
    english_name: 'Indonesia',
    native_name: 'Indonesia',
    image_id: 'ID',
  },
  {
    iso_3166_1: 'IE',
    english_name: 'Ireland',
    native_name: 'Ireland',
    image_id: 'IE',
  },
  {
    iso_3166_1: 'IT',
    english_name: 'Italy',
    native_name: 'Italy',
    image_id: 'IT',
  },
  {
    iso_3166_1: 'JP',
    english_name: 'Japan',
    native_name: 'Japan',
    image_id: 'JP',
  },
  {
    iso_3166_1: 'LT',
    english_name: 'Lithuania',
    native_name: 'Lithuania',
    image_id: 'LT',
  },
  {
    iso_3166_1: 'MX',
    english_name: 'Mexico',
    native_name: 'Mexico',
    image_id: 'MX',
  },
  {
    iso_3166_1: 'NL',
    english_name: 'Netherlands',
    native_name: 'Netherlands',
    image_id: 'NL',
  },
  {
    iso_3166_1: 'NZ',
    english_name: 'New Zealand',
    native_name: 'New Zealand',
    image_id: 'NZ',
  },
  {
    iso_3166_1: 'NO',
    english_name: 'Norway',
    native_name: 'Norway',
    image_id: 'NO',
  },
  {
    iso_3166_1: 'PH',
    english_name: 'Philippines',
    native_name: 'Philippines',
    image_id: 'PH',
  },
  {
    iso_3166_1: 'PL',
    english_name: 'Poland',
    native_name: 'Poland',
    image_id: 'PL',
  },
  {
    iso_3166_1: 'PT',
    english_name: 'Portugal',
    native_name: 'Portugal',
    image_id: 'PT',
  },
  {
    iso_3166_1: 'RU',
    english_name: 'Russia',
    native_name: 'Russia',
    image_id: 'RU',
  },
  {
    iso_3166_1: 'SK',
    english_name: 'Slovakia',
    native_name: 'Slovakia',
    image_id: 'SK',
  },
  {
    iso_3166_1: 'ZA',
    english_name: 'South Africa',
    native_name: 'South Africa',
    image_id: 'ZA',
  },
  {
    iso_3166_1: 'KR',
    english_name: 'South Korea',
    native_name: 'South Korea',
    image_id: 'KR',
  },
  {
    iso_3166_1: 'ES',
    english_name: 'Spain',
    native_name: 'Spain',
    image_id: 'ES',
  },
  {
    iso_3166_1: 'SE',
    english_name: 'Sweden',
    native_name: 'Sweden',
    image_id: 'SE',
  },
  {
    iso_3166_1: 'CH',
    english_name: 'Switzerland',
    native_name: 'Switzerland',
    image_id: 'CH',
  },
  {
    iso_3166_1: 'TR',
    english_name: 'Turkey',
    native_name: 'Turkey',
    image_id: 'TR',
  },
  {
    iso_3166_1: 'AE',
    english_name: 'United Arab Emirates',
    native_name: 'United Arab Emirates',
    image_id: 'AE',
  },
  {
    iso_3166_1: 'GB',
    english_name: 'United Kingdom',
    native_name: 'United Kingdom',
    image_id: 'GB',
  },
  {
    iso_3166_1: 'US',
    english_name: 'United States of America',
    native_name: 'United States',
    image_id: 'US',
  },
];
